services:

  photo-forum-angular-frontend:
    build:
      context: "./frontend - angular"
      dockerfile: Dockerfile
    volumes:
      - ./certs:/certs
    networks:
      - photo-forum-network
    ports:
      - "443:443"
    restart: always

  photo-forum-next-frontend:
    build:
      context: "./frontend - next.js"
      dockerfile: Dockerfile
    volumes:
      - ./certs:/certs
    networks:
      - photo-forum-network
    ports:
      - "8443:443"
    restart: always

networks:
  photo-forum-network:
    driver: bridge