services:

  photo-forum-angular-frontend:
    build:
      context: "./frontend - angular"
      dockerfile: Dockerfile
    volumes:
      - "./frontend - angular/src:/app/src"
    networks:
      - photo-forum-network
    ports:
      - "4200:4200"
    restart: always

  photo-forum-next-frontend:
    build:
      context: "./frontend - next.js"
      dockerfile: Dockerfile
    networks:
      - photo-forum-network
    ports:
      - "3000:3000"
    restart: always

networks:
  photo-forum-network:
    driver: bridge